name: Back-end CI/CD with Tests, SonarCloud & Docker

on:
  push:
    branches:
      - develop
    paths:
      - 'back/**'

  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'back/**'

jobs: