name: Front-end CI/CD with Tests, SonarCloud & Docker

on:
  push:
    branches:
      - develop
    paths:
      - 'front/**'

  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'front/**'

jobs: